# zledit extensibility config

[[previewers]]
pattern = '(OPS|DOC|ENG|IT)-[0-9]+'
description = 'Linear issues'
script = '~/.config/zledit/scripts/linear-preview.sh'

[[previewers]]
pattern = '^"?\$\{?[A-Za-z_][A-Za-z0-9_]*\}?"?$'
description = 'Env variable'
script = '~/.config/zledit/scripts/env-preview.sh'

[[previewers]]
pattern = '^[A-Za-z_][A-Za-z0-9_]*=.+'
description = 'Assignment'
script = '~/.config/zledit/scripts/assignment-preview.sh'

[[actions]]
binding = 'ctrl-o'
description = 'edit'
script = '~/.config/zledit/scripts/edit-file.sh'

[[actions]]
binding = 'ctrl-y'
description = 'yank'
script = '~/.config/zledit/scripts/yank.sh'
