[manager]
prepend_keymap = [
    { on = [ "g", "d" ], run = "cd ~/dev", desc = "cd to ~/dev" },
    { on = [ "g", "D" ], run = "cd ~/Downloads", desc = "cd to ~/Downloads" },
    { on = [ "g", "t" ], run = "cd ~/dev/talks", desc = "cd to ~/dev/talks" },
    { on = [ "g", "b" ], run = "cd /mnt/nas-backup/home", desc = "cd to NAS Backup Folder" },
    { on = [ "!" ], run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },
    { on = [ "m" ], run = "plugin bookmarks --args=save", desc = "Save current position as a bookmark" },
    { on = [ "'" ], run = "plugin bookmarks --args=jump", desc = "Jump to a bookmark" },
    { on = [ "b", "d" ], run = "plugin bookmarks --args=delete", desc = "Delete a bookmark" },
    { on = [ "b", "D" ], run = "plugin bookmarks --args=delete_all", desc = "Delete all bookmarks" },
    { on = [ "g", "f" ], run = 'search_do --via=fd --args="-E .git --type f"', desc = "Flat view files only (excludes .git)" }
]
